@startuml offboarding
autonumber "<b>0'.'"
box "Company1" #LightBlue
Participant "Company1\nEDC" as Company1EDC
Participant "Company1\nDID" as Company1DID
Participant "Company1\nIdentity Hub" as IDHUB1
end box

box "Dataspace Authority" #LightYellow
Participant "Registry API" as RAPI
Database "Participant\nRegistry" as Registry
end box

Company1EDC --> RAPI: send Offboarding request
group authorize request [Distributed authorization sub-flow]
  RAPI -> Company1DID
  RAPI -> IDHUB1
end
activate RAPI

RAPI --> Registry: delete Company1's DID URI
return status code
deactivate RAPI

@enduml